// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/il-landing/LandingPage.tsx": () => import("../components/mockups/il-landing/LandingPage.tsx"),
  "./components/mockups/il-landing/ServicesPage.tsx": () => import("../components/mockups/il-landing/ServicesPage.tsx")
};
